version: '3'

services:
  app:
    build: .
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./:/var/www/html
      - uploads_data:/var/www/app/public/uploads
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: camagru
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/sql:/docker-entrypoint-initdb.d

volumes:
  db_data:
  uploads_data: